### ISSUE TITLE
Could not open requirements file: [Errno 2]

### ISSUE THREAD

**Issue by lenskikh** [sdbds/audiocraft-webui#1]
Installing collected packages: mpmath, typing-extensions, sympy, networkx, MarkupSafe, filelock, jinja2, torch, torchaudio
Successfully installed MarkupSafe-2.1.3 filelock-3.12.1 jinja2-3.1.2 mpmath-1.3.0 networkx-3.1 sympy-1.12 torch-2.0.1+cu118 torchaudio-2.0.2+cu118 typing-extensions-4.6.3
Collecting xformers==0.0.20
  Downloading xformers-0.0.20-cp310-cp310-win_amd64.whl (97.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.6/97.6 MB 13.9 MB/s eta 0:00:00
Installing collected packages: xformers
Successfully installed xformers-0.0.20
**ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'**
Install requirement failed
Install failed

**Comment by sdbds** [comment]
sorry  for typo , just rename  requirement.txt to  requirements.txt

**Comment by sdbds** [comment]
i fixed it and you can update or just rename that txt

**Comment by lenskikh** [comment]
Thank you, it's working now.
