### ISSUE TITLE
Webui Player is not playing the generated audio

### ISSUE THREAD

**Issue by Karniverse** [sdbds/audiocraft-webui#6]
![image](https://github.com/sdbds/audiocraft-webui/assets/34996794/43fb31c5-61a5-49fd-abf7-b6bdf7f3c1b8)

i am able to play the .wav generated in temp folder but i couldnt play it in ui itself, can you help me fix this?

**Comment by sdbds** [comment]
plz provide your browser type and version
make sure if using lastest version with this repo.
if your webui is lastest version,you can try extend.ps1

**Comment by Karniverse** [comment]
> 

![image](https://github.com/sdbds/audiocraft-webui/assets/34996794/83b1a4d9-5c61-40ab-b266-7e8eb332d477)

sending you for reference, i'l try extend.ps1 and try on different browsers too and get back at this.

**Comment by Karniverse** [comment]
![image](https://github.com/sdbds/audiocraft-webui/assets/34996794/cbef04b7-0f25-4502-abf1-efd025b1def2)
i just checked it all browser chrome and edge latest versions, and tried extend.ps1, its the same issue.

**Comment by Karniverse** [comment]
i also noticed, .wav is generated, but something wrong with .mp4 merging, since .mp4 always with 0bytes

**Comment by Karniverse** [comment]
sorry i figured out, it was ffmpeg all along, i installed it properly, now it merges .wav into .mp4 and working perfect
