### ISSUE TITLE
app.py is missing [Errno 2]

### ISSUE THREAD

**Issue by GalenMarek14** [sdbds/audiocraft-webui#7]
app.py is missing [Errno 2]

> C:\Users\Özkan PC\AppData\Local\Programs\Python\Python310\python.exe: can't open file 'D:\\Audiocraft\\sdbdsWebUI\\audiocraft-webui\\audiocraft\\app.py': [Errno 2] No such file or directory

**Comment by sdbds** [comment]
i updated it now,you should run install.ps1 then use webui.ps1 to run

**Comment by GalenMarek14** [comment]
I tried install.ps1 but it gave this error:

> py : The term 'py' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
> spelling of the name, or if a path was included, verify that the path is correct and try again.
> At D:\Audiocraft\sdbdsWebUI\audiocraft-webui\install.ps1:24 char:10
> + $list = (py --list 2> $null)
> +          ~~
>     + CategoryInfo          : ObjectNotFound: (py:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
> 
> Install failed

**Comment by sdbds** [comment]
> I tried install.ps1 but it gave this error:
> 
> > py : The term 'py' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
> > spelling of the name, or if a path was included, verify that the path is correct and try again.
> > At D:\Audiocraft\sdbdsWebUI\audiocraft-webui\install.ps1:24 char:10
> > 
> > * $list = (py --list 2> $null)
> > * ```
> >        ~~
> >   ```
> >   
> >   
> >   
> >   * CategoryInfo          : ObjectNotFound: (py:String) [], CommandNotFoundException
> >   * FullyQualifiedErrorId : CommandNotFoundException
> > 
> > Install failed

i cant reproduce this error,so i suggest you Commented out these check version code from 23~40

[install.zip](https://github.com/sdbds/audiocraft-webui/files/13063060/install.zip)

**Comment by GalenMarek14** [comment]
Thank you so much for the help! Now it installs without a problem but this time webui.ps1 doesn't work, unfortunately. It gives this error, sorry for the trouble:

> Traceback (most recent call last):
>   File "D:\Audiocraft\sdbdsWebUI\audiocraft-webui\audiocraft\demos\musicgen_app.py", line 23, in <module>
>     from audiocraft.data.audio_utils import convert_audio
> ModuleNotFoundError: No module named 'audiocraft'

Thanks!

**Comment by sdbds** [comment]
i forgot install this ,update it and run,it will work

[install.zip](https://github.com/sdbds/audiocraft-webui/files/13063311/install.zip)

**Comment by GalenMarek14** [comment]
Thank you so much!
I tried every WebUI for days and this is the only one that worked. Thank you, especially for your fast responses :)

By the way, will you add audiogen too?

**Comment by sdbds** [comment]
> Thank you so much! I tried every WebUI for days and this is the only one that worked. Thank you, especially for your fast responses :)
> 
> By the way, will you add audiogen too?

sorry,i havent more time on this.
