### ISSUE TITLE
Musicgen stereo models

### ISSUE THREAD

**Issue by NeuroLord** [sdbds/audiocraft-webui#8]
How to use this webui with the new stereo models? It looks like the git has been updated, but there is no indication of this in the interface.
Also is it possible to use this with large-melody?

**Comment by sdbds** [comment]
![image](https://github.com/sdbds/audiocraft-webui/assets/8085926/2a65d7c2-a40c-4cce-854f-2483b3838bf4)
i had updated these,just choose stereo models

**Comment by NeuroLord** [comment]
Oh crap, I used a different implementation of the interface (extend.ps1). I apologize for the unnecessary opening of the issue
